#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    VOID,
    INT,
    SEMIC,
    LCURL,
    RCURL,
    LPAREN,
    RPAREN,
    RETURN,
    INTLITERAL,
    ADD,
    SUB,
    MUL,
    DIV,
    AND,
    OR,
    EQ,
    NE,
    LE,
    GE,
    LT,
    GT,
    ASSIGN,
    LOGNEG,
    IF,
    WHILE,
    FOR,
    ELSE,
    BREAK,
    CONTINUE,
    COMMA,
    MOD,
    CHAR,
    IDENT,
    EOF,
    ERR,
}

impl Token {
    pub fn from(value: usize) -> Token {
        match value {
            0 => Token::VOID,
            1 => Token::INT,
            2 => Token::SEMIC,
            3 => Token::LCURL,
            4 => Token::RCURL,
            5 => Token::LPAREN,
            6 => Token::RPAREN,
            7 => Token::RETURN,
            8 => Token::INTLITERAL,
            9 => Token::ADD,
            10 => Token::SUB, 
            11 => Token::MUL,
            12 => Token::DIV,
            13 => Token::AND,
            14 => Token::OR,
            15 => Token::EQ,
            16 => Token::NE,
            17 => Token::LE,
            18 => Token::GE,
            19 => Token::LT,
            20 => Token::GT,
            21 => Token::ASSIGN,
            22 => Token::LOGNEG,
            23 => Token::IF,
            24 => Token::WHILE, 
            25 => Token::FOR,
            26 => Token::ELSE,
            27 => Token::BREAK,
            28 => Token::CONTINUE,
            29 => Token::COMMA,
            30 => Token::MOD,
            31 => Token::CHAR,
            32 => Token::IDENT,
            33 => Token::EOF,
            _ => Token::ERR
        }
    }
}

pub static TOKEN_PATTERN: &'static [&'static str] = &[
    "void",
    "int",
    ";",
    "\\{",
    "\\}",
    "\\(",
    "\\)",
    "return ",
    "[0-9]+",
    "\\+",
    "\\-",
    "\\*",
    "\\/",
    "\\&\\&",
    "\\|\\|",
    "\\=\\=",
    "\\!\\=",
    "<\\=",
    ">\\=",
    "<",
    ">",
    "\\=",
    "\\!",
    "if",
    "while",
    "for",
    "else",
    "break",
    "continue",
    "\\,",
    "\\%",
    "char",
    "\\w+",
];